spring:
  application:
    name: discodeit

  config:
    import: optional:file:.env[.properties]  # .env 파일 자동 로드
    activate:
      on-profile: default

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # 없으면 기본 dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# actuator/info 에 노출할 정보
info:
  app:
    name: ${spring.application.name}
    description: Discodeit service (Actuator info)
    version: ${spring.application.version:1.7.0}
  runtime:
    profile: ${spring.profiles.active}
    java: ${java.runtime.version}
    jvmVendor: ${java.vendor}
    spring-boot: 3.5.4
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${storage.type}
    path: ${storage.path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}


# Actuator 노출 범위
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true   # liveness/readiness
  info:
    env:
      enabled: true     # info.* 노출
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

discodeit:
  storage:
    type: ${STORAGE_TYPE:local}