spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false  # 실행 쿼리 보기
    open-in-view: false # OSIV 비활성화
    hibernate:
      ddl-auto: validate  # (validate, update, create, create-drop 중 선택)
      naming: # 컬럼 명 매칭 방법
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: false # 실행 쿼리 포맷 형식으로 보기
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}
  presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)
